### ISSUE TITLE
Autofill in DuckDuckGo Browser

### ISSUE THREAD

**Issue by Holzhaus** [zeapo/Android-Password-Store#1160]
Domain-dependent Autofill in the [DuckDuckGo Android browser](https://github.com/duckduckgo/Android) does not work.

It always detects "DuckDuckGo" as search string, which makes a manual search necessary.

**Comment by msfjarvis** [comment]
This is trivial to fix but I just released 1.13.0 :\

**Comment by msfjarvis** [comment]
Umm, we already support DuckDuckGo. What Android version are you on?

**Comment by Holzhaus** [comment]
> Umm, we already support DuckDuckGo. What Android version are you on?

![Screenshot_20201022_145721](https://user-images.githubusercontent.com/1834516/96875215-436fdb80-1477-11eb-9332-3c0747e1d14e.jpg)

**Comment by Holzhaus** [comment]
Hold on, apparently my F-Droid just found some app updates. I'll try to reproduce with the latest versions and closes this if it's already fixed.

**Comment by Holzhaus** [comment]
I can still reproduce it with DDG 5.67.0 sc   (56700) and Password Store 1.11.3.

![Screenshot_20201022_151245.jpg](https://user-images.githubusercontent.com/1834516/96876710-13293c80-1479-11eb-8605-cd6bfa6ce7a3.jpg)

**Comment by Holzhaus** [comment]
> This is trivial to fix but I just released 1.13.0 :\

Maybe the F-Droid version is just outdated?

**Comment by msfjarvis** [comment]
> > This is trivial to fix but I just released 1.13.0 :\
> 
> Maybe the F-Droid version is just outdated?

Shouldn't matter, DDG support has been there since day one of the feature's introduction. FWIW, Autofill works correctly in DDG on my Samsung device.

**Comment by Holzhaus** [comment]
> > > This is trivial to fix but I just released 1.13.0 :\
> > 
> > 
> > Maybe the F-Droid version is just outdated?
> 
> Shouldn't matter, DDG support has been there since day one of the feature's introduction. FWIW, Autofill works correctly in DDG on my Samsung device.

What do I need to do to debug this? I'm not really familiar with development on Android.

**Comment by fmeum** [comment]
Just give me the link or APK you installed DuckDuckGo from and I'll take a look.

**Comment by fmeum** [comment]
Could you try again with the Play Store version of DuckDuckGo?

@msfjarvis There is a simple explanation: The Play Store and f-droid versions of DuckDuckGo have the same application ID, but different signatures. The one known to Autofill is the Play Store signature. Should we support multiple signatures per app or wait for other real-world examples of this first?

**Comment by msfjarvis** [comment]
> Could you try again with the Play Store version of DuckDuckGo?
> 
> @msfjarvis There is a simple explanation: The Play Store and f-droid versions of DuckDuckGo have the same application ID, but different signatures. The one known to Autofill is the Play Store signature. Should we support multiple signatures per app or wait for other real-world examples of this first?

It's not going to be a very common case since everybody's browsers are now built on Chromium which F-Droid will never manage to build, but it is certainly a case we should try to support if it's doable without complicating things too much.

**Comment by msfjarvis** [comment]
Turns out this was rather trivial to support this.
